/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxAsclin_Asc.h"
#include "VCOM.h"

#include "util.h"
#include "lock_example.h"


IfxCpu_syncEvent g_cpuSyncEvent = 0;

//LMU Noise Element
volatile unsigned int * test_data = 0xB000001C;


/*Quick Brown Fox Jumps Over Dog"*/
char Core0_Word1 [] = "Quick ";
char Core0_Word2 [] = "Brown ";

void Set_LEDs(void);

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    Set_LEDs();

    initVCOMSerialInterface();

    /* Wait for CPU sync event */
    //IfxCpu_emitEvent(&g_cpuSyncEvent);
    //IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

#if USE_LOCKS
    GetLock();
#endif

    synchronizeOtherCores();
    
    *test_data = 2;

    VCOM_Core_Write(&Core0_Word1[0]);
    VCOM_Core_Write(&Core0_Word2[0]);

#if USE_LOCKS
    ReleaseLock();
#endif

    while(1)
    {
        *test_data = 3;
    }
    return (1);
}

void Set_LEDs(void)
{
    IfxPort_setPinMode(&MODULE_P13, 0, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(&MODULE_P13, 1, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(&MODULE_P13, 2, IfxPort_Mode_outputPushPullGeneral);

    IfxPort_setPinState(&MODULE_P13, 0, IfxPort_State_high);
    IfxPort_setPinState(&MODULE_P13, 1, IfxPort_State_high);
    IfxPort_setPinState(&MODULE_P13, 2, IfxPort_State_high);
}
